### ISSUE TITLE
Tweak guns like Shotgun and Revolver

### ISSUE THREAD

**Issue by MotoRunner117** [Hedgefog/cs-zombie-panic#12]
Shotgun has too much spread and takes 6 shots to kill a zombie, Magnum feels powerful but also very inaccurate.

Btw i think a discord server for cs zp1 or steam group would be very good to bring more players in

**Comment by Hedgefog** [comment]
Thanks!
I've reduced the shotgun spread, now It's more accurate.
Magnum has no spread and shoots directly to the crosshair position.

**Comment by MotoRunner117** [comment]
Thanks, i think Magnum feels like that because the crosshair is pretty big, perhaps make it very small if it works  ?

**Comment by Hedgefog** [comment]
Unfortunately, there is no way to change crosshair, the sprite crosshair is not supported by Counter-Strike.
I came across a bug that allows you to change the crosshair at the "death" time using a weapon hud document, perhaps somehow it will be possible to reproduce it.

**Comment by Hedgefog** [comment]
Steam group: https://steamcommunity.com/groups/cs-zombie-panic

**Comment by MotoRunner117** [comment]
Another thing i noticed is that there's barely any blood coming out when you shoot zombies, it actually has yellow blood oike from hl1 mobs, the original zp1 had lots of blood

**Comment by Hedgefog** [comment]
It looks like you are using custom sprites in your client. I haven't changed any blood sprites.

**Comment by Hedgefog** [comment]
Custom crosshairs - implemented ✔
