### ISSUE TITLE
предложка по обнове

### ISSUE THREAD

**Issue by MoLoD228** [Hedgefog/cs-zombie-panic#49]
1)- сделать русский язык , сделать руководство по инструкции игры в самой игре, где будет написано что и как делать куда бежать .
2)- сделать датчик движения для кт, купил датчик в магазини пошел в коридор установил и когда зомби попадается на датчик тот кто поставил его ему пишется в чат что сработал датчик , и он будет знать что зомби рядом 
3)- сделать так чтобы  не автоматически хп восстанавливалось , а чтобы надо было убить 1 из кт и нажать на его труп чтобы зомби начал пожерать его труп, и тем самым пополнел себе хп. и чтобы была анимация как он его жрёт
4)- сделать голосовое сопровождение где тебе будут говорить что и как делать , и другое что нибудь 
5)- добавить возможность кричать зомбику чтобы нажал на кнопку он крикнул и чтоб кт тоже могли смешные фразы говорить , по типу , ты чо здесь вылупился  щяс на мясо пущу .
6)- сделать питомцев с системой уровней , допустим купил пета ты можешь надевать на него разные украшения веци и тд , питомец будет бегать со время рядом с тобой 1 уровень питомец может унюхать  что по близости где то  лежат патроны, 2 уровень он может также сообщить где по близости лежит ствол , 3 уровень он может унюхать что рядом зомби и сообщить хозяину об опасности, 4 уровень у него появится способность  давать хозяину патроны когда у него они закончились только это питомец может сделать раз в 20 минут. 5 уровень  он сможет укусить зомби если он напал на хозяина и тем самым он чучуть поможет хозяину убить зомби .( чтобы питомец прокачивался и у него прибавлялся уровень ему необходимо давать кости которые иногда выпадают из труппа зомби )
7 добавить одного зомби босса который выбирается по рандому,  у данного босса будет побольше хп и увеличенная скорость бега, и у него будет 2 жизни , если он их истратил он больше не сможет воскристится до конца раунда и его простые зомби больше не смогут много раз и так часто бить руками так как их пос погиб они слабее и могут только раз в 4 секунды ударить  кт.

**Comment by Hedgefog** [comment]
1. Подсказки и русский язык уже частично реализованы.
3. В этом нет смысла, зомби будет проще умереть для перерождения, чем искать возможность восстановить здоровье.
4. Такое можно реализовать на картах, так что если у мода будет активное сообщество, думаю, что таки карты могут появится.
5. В будущем будут добавлены радио-команды, где будут и немного насмешек, так же возможно будут автоматические насмешки, срабатывающие при каких-то игровых событиях.
2, 6. Такие вещи не соответствуют концепции модификации, так как основное ее направление - хардкор, однако не стоит исключать появление дополнительных плагинов для мода от сторонних авторов.
7. Планируется добавление Carrier-зомби с увеличенным запасом здоровья, уроном, скоростью и возможность инфицировать выживших, которые будут превращаться в зомби через некоторое время. Этот класс будет выдаваться игроку, который стал первым зомби в раунде.
