### ISSUE TITLE
Condition Zero World Texture error

### ISSUE THREAD

**Issue by xLeviNx** [Hedgefog/cs-zombie-panic#72]
Get a lot of errors from running this on cs:cz. All the right dependencies are installed:

```

No detail texture mapping file: maps/w_weaponbox_detail.txt
Mod_LoadBrushModel: models/zombiepanic/v100/items/w_weaponbox.mdl has wrong version number (1329865020 should be 30)

No detail texture mapping file: maps/lightcone_detail.txt
Mod_LoadBrushModel: models/zombiepanic/v100/lightcone.mdl has wrong version number (1329865020 should be 30)

Client world model is NULL
Client world model is NULL
```

**Comment by Hedgefog** [comment]
Please, send me a list of installed plugins

P.S: Did you put models into the map folder?

**Comment by xLeviNx** [comment]
It's running all off the defaulted plugins in zombie panic ini file, and the default amxmodx plugins. Sadly I can't list the amxx plugins since my console doesn't output anything (the panel I have uses scrds protocol, not hlds). 

Models in the maps folder? I just dragged and dropped the resources from 1.3.0 into the appropriate folders

**Comment by Hedgefog** [comment]
Did you install RegameDLL and ReAPI?

**Comment by Hedgefog** [comment]
I've just downloaded `czero` server using `steamcmd`, installed rehlds, regamedll, reapi and the latest mod build from github, works without any issues. Try to make clean install, don't forget to install `mp.dll` to the `czero/dlls` folder

**Comment by xLeviNx** [comment]
> Did you install RegameDLL and ReAPI?

Yes, both were installed.

> I've just downloaded `czero` server using `steamcmd`, installed rehlds, regamedll, reapi and the latest mod build from github, works without any issues.
> Try to make a clean install, don't forget to install `mp.dll` to the `czero/dlls` folder.

I'll try this again. May be related to https://github.com/ValveSoftware/halflife/issues/74

**Comment by Hedgefog** [comment]
This may be a problem with the downloaded archive, try to download it again. If that doesn't work, try downloading using a different browser or extract it using a different extractor.
